<a href="https://colab.research.google.com/github/yongshidanke/pytorch_learning/blob/main/day01/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Wed Jul  9 07:20:46 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#00.The journey to Pytorch

resource:https://docs.pytorch.org/tutorials

## 01.tensor:

In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [4]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data but contains the same form
print(f"Random Tensor: \n {x_rand} \n")

x_rand


Random Tensor: 
 tensor([[0.0588, 0.0960],
        [0.9199, 0.2996]]) 



tensor([[0.0588, 0.0960],
        [0.9199, 0.2996]])

In [5]:
x_rand[1,1]=0.128

print(x_rand)

tensor([[0.0588, 0.0960],
        [0.9199, 0.1280]])


In [6]:
tensor=torch.ones(4,3)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = torch.stack([tensor, tensor, tensor], dim=1)
t3 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
print(t2)
print(t3)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [7]:
y1 = tensor @ tensor.T#转置
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)#点乘


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

##02.Autograd

In [8]:
import torch

In [35]:
x=torch.randn(3,requires_grad=True)
print(x)
y=torch.randn(3,2,requires_grad=True)
b = torch.randn(2, requires_grad=True)
z1=torch.matmul(x,y)+b
z2=torch.ones(2)
loss = torch.nn.functional.binary_cross_entropy_with_logits(z1,z2)
loss.backward()
x.grad




tensor([-0.0938,  0.6352,  0.3867], requires_grad=True)


tensor([-0.4058,  0.3506,  0.6310])